version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_v8
    restart: always
    ports:
      - "33060:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ~/.docker_data/mysql80:/var/lib/mysql
    networks:
      - common

networks:
  common:
    external: true
